const fields=[['情感关系','♡','未来三个月，我们的关系可能如何发展？我需要看清什么？'],['事业发展','♜','在当前事业阶段，我最需要看见的机会与阻碍是什么？'],['学业考试','✎','为了更稳妥地达成学习目标，我现在应调整什么？'],['财务状况','◇','我该如何理解并改善目前与金钱的关系？'],['人际关系','♧','在这段人际关系中，我需要建立怎样的边界？'],['人生抉择','⇄','面对这个选择，什么因素最值得我认真衡量？'],['今日指引','☼','今天我最需要关注的内在主题是什么？']];
const spreads=[{id:'one',name:'单牌指引',count:1,desc:'适合今日提醒或一个清晰、轻量的问题。',positions:['此刻的指引']},{id:'three',name:'三牌阵',count:3,desc:'适合看见事情的脉络：现状、阻碍与建议。',positions:['现状','阻碍','建议']},{id:'five',name:'五牌抉择',count:5,desc:'适合比较两个选项，不替你决定，但照见各自代价。',positions:['你的核心需要','选项 A 的动力','选项 A 的代价','选项 B 的动力','选项 B 的代价']},{id:'celtic',name:'凯尔特十字',count:10,desc:'适合复杂、长期、牵涉多重因素的问题。',positions:['核心现状','交叉挑战','意识目标','深层根源','近期过去','近期趋势','你的姿态','外部环境','希望与恐惧','整合方向']}];
const domainNames=['情感关系','事业发展','学业考试','财务状况','人际关系','人生抉择','个人成长','今日指引'];
const elementProfiles={火:{energy:'火元素代表意愿、行动、热情、创造力与生命冲动。它推动事情发生，也提醒你观察冲动是否已经超过承载力。',gift:'主动表达、快速推进、重燃热情',shadow:'急躁消耗、过度证明、三分钟热度'},水:{energy:'水元素代表情绪、关系、直觉、共情与内在流动。它让人靠近真实感受，也容易让边界变得模糊。',gift:'感受力、疗愈、连接与接纳',shadow:'情绪淹没、投射、逃避现实'},风:{energy:'风元素代表思想、判断、沟通、冲突与清晰度。它帮助你把混乱说清楚，也可能让人困在过度分析里。',gift:'辨析、沟通、策略与清醒',shadow:'焦虑反刍、语言伤人、理性防御'},土:{energy:'土元素代表身体、金钱、资源、秩序与现实结果。它要求事情落地，也提醒你照顾长期稳定。',gift:'稳定、积累、执行与安全感',shadow:'停滞、匮乏感、过度控制'},灵:{energy:'灵性元素代表人生阶段、原型力量、命运转折与深层意识。它不指向单一事件，而是提醒你看见更大的课题。',gift:'整合、觉醒、意义与方向',shadow:'宿命化、逃避选择、把主动权交给外界'}};
const numberProfiles={0:['零','空白、自由与未知入口','允许自己以初学者之心进入，不急着定义结果'],1:['一','种子、意志、开始与聚焦','把能量收束到一个最小可执行动作'],2:['二','关系、选择、平衡与镜像','先辨认两股力量，再决定是否需要调和'],3:['三','表达、创造、协作与初步成形','让想法进入互动，不要只在心里排练'],4:['四','结构、稳定、边界与停留','检查秩序是在保护你，还是困住你'],5:['五','冲突、变化、失衡与调整','把摩擦当作信号，找到真正需要修正的地方'],6:['六','修复、互助、过渡与重新对齐','允许帮助进入，也练习把善意落实成行动'],7:['七','评估、选择、坚持与内在考验','区分真实阻力与内心防御，保留必要的耐心'],8:['八','力量、循环、专注与推进','重复练习会带来质变，但也要避免机械内耗'],9:['九','积累、临界、独处与成果前夜','看见自己已经走到哪里，同时保留最后的清醒'],10:['十','完成、承担、转化与新周期前的负荷','完成不等于继续硬扛，该交接的需要交接'],11:['侍从','学习者、消息、试探与新的兴趣','用轻量实验代替一次性承诺'],12:['骑士','行动者、追寻、速度与方向','检查你的速度是否服务于目标'],13:['王后','滋养、承接、成熟的内在力量','用稳定的照顾让资源自然生长'],14:['国王','掌控、责任、外在结构与领导','用成熟规则保护愿景，而不是压制生命力']};
const fieldTemplates={情感关系:['这张牌把关系焦点放在「{core}」。它更适合观察互动模式、依恋需求与边界，而不是替你断言对方的绝对想法。','留意关系中是否存在「{shadow}」。先把感受说清楚，再讨论承诺、距离或下一步。'],事业发展:['在事业里，它提示你审视「{core}」如何影响机会、节奏与协作。','把目标拆成可验证节点，避免被「{shadow}」拖慢判断。'],学业考试:['在学习中，它强调「{core}」对专注、方法和信心的影响。','今天先修正一个具体学习动作，别用焦虑替代复盘。'],财务状况:['在财务议题里，它关注「{core}」与安全感、资源分配之间的关系。','所有决定先回到事实、预算和风险边界，避免让「{shadow}」主导消费或投资。'],人际关系:['在人际中，它显示「{core}」如何影响沟通、信任和边界。','减少揣测，选择一次具体、低攻击性的表达。'],人生抉择:['在选择题里，它提醒你比较不同道路背后的「{core}」与代价。','不要急着寻找完美答案，先定义你愿意承担什么。'],个人成长:['在成长层面，它指向你正在学习整合的「{core}」。','把注意力从证明自己转向理解自己的惯性。'],今日指引:['今天它提醒你温柔关注「{core}」。','只做一个小动作：让身体、情绪或现实秩序稍微回到你手里。']};
const majorSeeds=[
  ['愚人','✧','灵',0,'背着小包的人站在崖边，白犬提醒本能，远山象征未展开的旅程。','自由、信任、冒险精神与尚未被经验框住的新阶段。','在不确定中保留开放，允许自己开始。','冲动逃避现实、拒绝承担后果，或把未知浪漫化。','为一个新方向做低风险试走，不要一次押上全部。','我是真的自由，还是在用自由回避承诺？'],
  ['魔术师','✦','风',1,'桌上摆着四元素工具，一手指天一手指地，象征把意图带入现实。','意志、资源整合、语言影响力与创造的第一推动。','你手上已有足够材料，关键是聚焦并行动。','能力分散、操控他人，或只会表达却不落地。','列出已有资源，今天完成一个能被看见的产出。','我是否把能量用在创造，而不是证明自己？'],
  ['女祭司','☾','水',2,'她坐在黑白柱之间，帷幕后有未显露的知识，卷轴代表内在智慧。','直觉、沉默、潜意识、等待与尚未公开的信息。','先静观，不急于逼问答案；答案正在内在成形。','过度封闭、逃避沟通，或把直觉和恐惧混为一谈。','给自己一段不被打扰的时间，记录梦、身体感受和反复出现的念头。','我听见的是直觉，还是焦虑披上的神秘外衣？'],
  ['皇后','❀','土',3,'丰盛花园、麦田与柔软坐席象征滋养、身体和自然生长。','滋养、丰盛、创造、关系中的接纳与身体智慧。','让事物在被照顾中自然成长，不必用紧绷换结果。','过度付出、依赖被需要，或把照顾变成控制。','今天照顾一个具体需求：饮食、睡眠、空间或情绪。','我是在滋养自己，还是只是在满足别人对我的需要？'],
  ['皇帝','♜','火',4,'石座、权杖与山脉象征边界、秩序、责任和可持续结构。','规则、领导、承担、边界与长期稳定的框架。','建立清晰规则会让混乱重新有形。','僵化控制、权威压迫，或害怕失控而拒绝柔软。','写下一条必须被尊重的边界，并用平静方式执行。','我的规则是在保护生命力，还是在压制它？'],
  ['教皇','⚜','土',5,'导师坐在圣殿中，两名求学者聆听，象征传统、传承与共同信念。','学习、价值观、制度、导师关系与群体规范。','向成熟系统学习，别独自重复试错。','教条依赖、害怕异端，或把外部认可当作唯一真理。','找一个可靠框架或前辈建议，再结合你的真实处境筛选。','我相信的规则，仍然服务于现在的我吗？'],
  ['恋人','♡','风',6,'两个人站在天使之下，既象征吸引，也象征价值选择。','联结、选择、诚实、关系中的对齐与自我确认。','真正的选择需要价值一致，而不只是情绪吸引。','摇摆逃避、关系失衡，或为了被爱而背离自己。','说出一个真实需要，同时尊重对方回应的自由。','我正在选择爱，还是选择被需要的感觉？'],
  ['战车','♞','水',7,'驾车者掌控两股方向不同的力量，城市在身后，前路在脚下。','意志推进、自我掌控、目标感与情绪驾驭。','把分散的力量拉回同一方向，事情会开始推进。','急进、内耗、方向不一，或只想赢却忘了为何出发。','明确一个短期目标和停止线，避免盲目加速。','我想抵达哪里？现在的速度真的适合那里吗？'],
  ['力量','∞','火',8,'女子温柔合上狮口，象征用接纳而非压制来整合本能。','温柔勇气、自我调节、耐心与稳定的内在力量。','真正的力量来自安抚本能，而不是消灭脆弱。','压抑欲望、自我怀疑，或用强撑掩饰恐惧。','用温和但坚定的方式处理一件让你紧张的事。','我是否允许自己既柔软又有力量？'],
  ['隐士','☼','土',9,'老人提灯独行山巅，灯光照亮脚下一小段路。','独处、内省、经验沉淀、寻找自己的光。','暂时远离噪音，答案会在安静里变清楚。','孤立回避、拒绝求助，或把退缩伪装成成熟。','减少外部输入，写下你真正相信的三个判断。','我是在独处中靠近自己，还是在孤立中惩罚自己？'],
  ['命运之轮','⊙','灵',10,'轮盘、四方守护者与升降的形象象征周期、转折和无常。','周期变化、机会窗口、因果流动与不可控因素。','形势正在转动，顺势调整比强行抓住更重要。','重复旧模式、抗拒变化，或把一切推给命运。','观察最近重复出现的信号，调整一个过时策略。','我能改变哪一部分，又需要接受哪一部分正在变化？'],
  ['正义','⚖','风',11,'人物手持天秤与剑，象征清醒判断、责任和事实。','公平、因果、契约、诚实与清晰边界。','回到事实与责任，答案会比情绪更稳定。','偏见、逃避后果，或只想证明自己正确。','把事实、感受、责任分三栏写下，再做决定。','如果完全诚实，我需要承认什么？'],
  ['倒吊人','▽','水',12,'人倒挂树上却面容平静，光环显示换位后的洞见。','暂停、牺牲、换角度、让旧执念松动。','暂缓推进会带来新的理解，不是所有停顿都等于失败。','被动拖延、自我牺牲成瘾，或迟迟不愿选择。','暂停一次惯性反应，从对方或未来自己的视角重看问题。','我放不下的是目标，还是对控制感的依赖？'],
  ['死神','♱','水',13,'骑士经过旧身份的倒下，远处太阳升起，象征结束后的更新。','结束、蜕变、清理、不可逆的阶段转换。','某个旧阶段已经完成，给新空间让位。','留恋旧壳、害怕失去，或拖延必要告别。','清理一个已经失效的承诺、物品或期待。','我真正害怕的是结束，还是结束后不知道自己是谁？'],
  ['节制','⚗','火',14,'天使在两杯之间调和水流，一脚入水一脚在岸。','调和、疗愈、节奏、整合差异与长期修复。','不必极端选择，稳定调配会带来恢复。','过度、失序、节奏混乱，或试图强行融合不相容的部分。','把计划调整到可持续强度，而不是理想强度。','我是否允许修复以缓慢但真实的方式发生？'],
  ['恶魔','♑','土',15,'两人被松垮锁链束缚，恶魔象征欲望、依附和被放大的恐惧。','欲望、成瘾、束缚、权力交换与阴影诚实。','看见束缚，才可能重新拿回选择权。','否认沉溺、羞耻循环，或把依赖误认为命运。','识别一个让你失去自由的习惯，并设置现实限制。','我从这个束缚里得到什么隐秘好处？'],
  ['高塔','ϟ','火',16,'雷电击中高塔，人物坠落，虚假结构突然瓦解。','真相冲击、结构崩塌、清醒与重建前的破裂。','不稳的东西正在被揭穿，痛感来自旧结构失效。','恐惧改变、抓住废墟，或用否认延长崩塌。','停止粉饰问题，先处理最核心的风险点。','哪件事其实早有裂缝，只是我不愿承认？'],
  ['星星','✵','风',17,'女子向水与土地倾倒清泉，星光象征希望、疗愈与重新信任。','希望、疗愈、灵感、真诚展露与长期恢复。','请相信缓慢恢复的力量，你正在重新连接生命感。','失望疏离、理想落空，或把希望寄托得太远。','做一件让身心恢复干净感的小事，并减少自我否定。','我如何在不逃避现实的前提下，重新允许希望？'],
  ['月亮','☽','水',18,'月光下的犬、狼、河蟹与小径象征梦境、恐惧和潜意识迷雾。','潜意识、暧昧、恐惧投射、梦与未明朗信息。','现在不适合草率定论，先分清事实与想象。','焦虑误读、沉溺幻想，或被不确定性牵着走。','把事实、推测、感受分开记录，推迟重大判断。','我害怕的画面，有多少来自现实证据？'],
  ['太阳','☀','火',19,'孩子骑白马在阳光下前行，向日葵象征生命力和坦诚。','清晰、喜悦、生命力、公开与简单直接的真相。','事情正在变得明亮，真诚表达会带来力量。','自负、过度曝光，或用乐观掩盖细节。','选择一种直接、坦诚、不过度解释的沟通方式。','我是否允许快乐简单地存在，而不急着怀疑它？'],
  ['审判','♬','火',20,'号角唤醒沉睡者，象征召唤、复盘和重新回应生命。','觉醒、召唤、复盘、宽恕与阶段性重生。','你正在听见一个更真实的召唤，需要回应而非拖延。','自责、逃避召唤，或反复审判自己和他人。','完成一次诚实复盘：我学到了什么，下一步如何不同？','如果不再惩罚过去的自己，我会如何选择？'],
  ['世界','◎','土',21,'舞者位于花环中央，四方守护者环绕，象征完成与整合。','完成、整合、成熟、归属与一个周期的圆满。','你已经走完一段重要旅程，可以带着成果进入新阶段。','未竟感、封闭循环，或害怕结束后的空白。','为一个阶段做正式收尾：总结、告别、交付或庆祝。','我是否愿意承认自己已经完成了某些成长？']
];
const suits=[{name:'权杖',icon:'♢',element:'火',theme:'行动、热情与创造力',symbol:'权杖像发芽的木杖，象征意志从身体里升起，渴望把想法点燃成行动。',domain:'热情、创造、目标、竞争、事业动力',action:'把灵感落成一个可执行动作，先开始，再调整。'},{name:'圣杯',icon:'♧',element:'水',theme:'情绪、关系与感受',symbol:'圣杯承接水流，象征心的容量、情绪交换、亲密与直觉。',domain:'情感、疗愈、关系、共情、内在需要',action:'先承认真实感受，再决定如何表达和靠近。'},{name:'宝剑',icon:'♤',element:'风',theme:'思想、沟通与冲突',symbol:'宝剑切开迷雾，象征语言、判断、边界和思想带来的清醒。',domain:'沟通、决定、冲突、分析、信念系统',action:'用事实和清晰表达替代猜测与反复内耗。'},{name:'星币',icon:'⬡',element:'土',theme:'现实、资源与身体',symbol:'星币落在手中，象征金钱、身体、时间、技能和可累积的现实价值。',domain:'金钱、工作、健康、资源、长期建设',action:'把问题落到预算、时间表、身体状态和可验证结果上。'}];
const ranks=[['王牌',1,'新的开端','种子被交到手中，潜能尚小但方向清晰。'],['二',2,'选择与平衡','两股力量彼此牵引，需要协调节奏。'],['三',3,'发展与协作','初步成果显现，需要表达、协作或扩展。'],['四',4,'稳定与停留','结构形成，但也可能让流动变慢。'],['五',5,'摩擦与调整','冲突暴露问题，也带来重新排序的机会。'],['六',6,'过渡与互助','能量开始修复，关系或状态走向更平衡。'],['七',7,'评估与坚持','内在考验出现，需要选择真正值得守护的方向。'],['八',8,'推进与限制','重复、速度和专注带来推进，也可能形成压力。'],['九',9,'积累与临界','经验接近成熟，仍需最后的耐心与辨别。'],['十',10,'完成与负担','一个周期走到高点，成果和责任同时出现。'],['侍从',11,'探索与消息','学习者带来新消息、新兴趣和试探性的开始。'],['骑士',12,'行动与追寻','行动者带来速度、方向和需要校准的冲劲。'],['王后',13,'内在掌握','成熟的承接力，让能量在稳定中生长。'],['国王',14,'成熟与承担','外在掌控与责任，要求把经验变成规则。']];
function buildFieldMeanings(core,shadow){return Object.fromEntries(domainNames.map(name=>[name,fieldTemplates[name].map(text=>text.replace('{core}',core).replace('{shadow}',shadow)).join('')]))}
function buildMajorCard(seed){const [name,icon,element,number,symbol,core,upright,reversed,actionAdvice,selfInquiry]=seed,numberProfile=numberProfiles[number]||[String(number),'阶段性课题','观察此阶段正在要求你成熟的部分'],elementProfile=elementProfiles[element];return{id:`M${number}`,name,icon,arcana:'大阿卡纳',element,number,upright,reversed,theme:core,symbolism:symbol,numberMeaning:`${numberProfile[0]}号牌：${numberProfile[1]}。${numberProfile[2]}。`,elementEnergy:elementProfile.energy,uprightText:upright,reversedText:reversed,fieldMeanings:buildFieldMeanings(core,elementProfile.shadow),actionAdvice,reflectionQuestion:selfInquiry,selfInquiry}}
function buildMinorCard(suit,suitIndex,rank,rankIndex){const [rankName,number,core,rankSymbol]=rank,elementProfile=elementProfiles[suit.element],name=`${suit.name}${rankName}`,shadow=`${elementProfile.shadow}在“${core}”上的表现`,upright=`${name}正位表示${suit.theme}进入「${core}」阶段。它不是抽象好运，而是提醒你把${suit.domain}中的关键线索落实到可观察的选择里。`,reversed=`${name}逆位表示${shadow}：能量可能卡住、过度或方向失衡，需要先修正节奏与边界。`,actionAdvice=`${suit.action}围绕「${core}」设定一个今天能完成的小步骤，并观察现实反馈。`,selfInquiry=`在${suit.domain}里，我面对「${core}」时最容易诚实，还是最容易逃避？`;return{id:`${suitIndex}-${rankIndex}`,name,icon:suit.icon,arcana:suit.name,element:suit.element,number,upright,reversed,theme:`${suit.theme}；${core}`,symbolism:`${suit.symbol}${rankSymbol}`,numberMeaning:`${numberProfiles[number]?.[0]||rankName}：${numberProfiles[number]?.[1]||core}。${numberProfiles[number]?.[2]||'观察这股能量如何要求你做出成熟回应'}。`,elementEnergy:elementProfile.energy,uprightText:upright,reversedText:reversed,fieldMeanings:buildFieldMeanings(`${suit.theme}中的${core}`,shadow),actionAdvice,reflectionQuestion:selfInquiry,selfInquiry}}
const majors=majorSeeds;
const cards=[...majorSeeds.map(buildMajorCard),...suits.flatMap((s,si)=>ranks.map((r,ri)=>buildMinorCard(s,si,r,ri)))];
let state={field:fields[0][0],question:'',spread:null,shuffled:false,cut:false,drawn:[],revealIndex:0};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function secureRandom(max){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%max}
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=secureRandom(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function renderFields(){$('#fieldGrid').innerHTML=fields.map((f,i)=>`<button class="field-card ${i===0?'selected':''}" data-field="${f[0]}"><i>${f[1]}</i><span>${f[0]}</span></button>`).join('');$$('.field-card').forEach(b=>b.onclick=()=>{$$('.field-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.field=b.dataset.field;const f=fields.find(x=>x[0]===state.field);$('#question').placeholder=`例如：${f[2]}`})}
function renderSpreads(){$('#spreadGrid').innerHTML=spreads.map(s=>`<button class="spread-card" data-spread="${s.id}"><span class="count">${s.count} 张牌</span><div class="spread-visual">${Array.from({length:Math.min(s.count,6)},()=>'<i></i>').join('')}</div><h3>${s.name}</h3><p>${s.desc}</p></button>`).join('');$$('.spread-card').forEach(b=>b.onclick=()=>{$$('.spread-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.spread=spreads.find(s=>s.id===b.dataset.spread);$('#toDraw').disabled=false})}
function goStage(n){$$('.reading-stage').forEach(s=>s.classList.toggle('active',+s.dataset.stage===n));$$('.progress-step').forEach((s,i)=>{s.classList.toggle('active',i===n-1);s.classList.toggle('done',i<n-1)});document.querySelector('#reading').scrollIntoView({behavior:'smooth'});if(n===3)renderDeck()}
function checkCooldown(){const q=state.question.trim().toLowerCase();if(!q)return false;const records=JSON.parse(localStorage.getItem('moonTarotRecords')||'[]');const recent=records.find(r=>r.question.trim().toLowerCase()===q&&Date.now()-r.timestamp<21600000);return recent}
function renderDeck(){const table=$('#deckTable');table.innerHTML=Array.from({length:26},(_,i)=>`<button class="deck-card" aria-label="选择第 ${i+1} 张牌" style="transform:translateX(${(i-12.5)*Math.min(15,260/26)}px) rotate(${(i-12.5)*.8}deg);z-index:${i}" data-index="${i}"></button>`).join('');$$('.deck-card').forEach(c=>c.onclick=()=>chooseCard(c));$('#drawStatus').textContent=state.shuffled?(state.cut?'请从牌面中亲手选择':'你可以切一次牌，然后开始选择'):'准备好后，请先洗牌'}
function chooseCard(el){if(!state.shuffled)return toast('请先洗牌');if(!state.cut)return toast('先完成一次切牌，让选择更有仪式感');if(state.drawn.length>=state.spread.count)return;const remaining=cards.filter(c=>!state.drawn.some(d=>d.id===c.id));const card=remaining[secureRandom(remaining.length)],isReversed=$('#reversalToggle').checked&&secureRandom(2)===1;state.drawn.push({...card,reversed:isReversed?card.reversed:false});el.classList.add('chosen');const left=state.spread.count-state.drawn.length;$('#drawStatus').textContent=left?`已选择 ${state.drawn.length} 张，还需 ${left} 张`:`已选好 ${state.spread.count} 张牌。准备好后，逐张翻开。`;$('#revealButton').disabled=left!==0}
function elementInsight(){const counts={};state.drawn.forEach(c=>counts[c.element]=(counts[c.element]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];const major=state.drawn.filter(c=>c.arcana==='大阿卡纳').length;return `${top?`${top[0]}元素最突出，说明当前议题尤其牵动${{火:'行动与意愿',水:'情绪与关系',风:'思考与沟通',土:'现实与安全感',灵:'深层人生课题'}[top[0]]}。`:''}${major>=Math.ceil(state.drawn.length/2)?'大阿卡纳占比较高，这更像一次需要认真整合的人生课题，而非短暂波动。':'这组牌更关注可以被日常行动调整的具体处境。'}`}
function cardMeaning(c,i){const pos=state.spread.positions[i],orientation=c.reversed?'逆位':'正位',core=c.reversed?c.reversedText:c.uprightText,fieldText=c.fieldMeanings?.[state.field]||c.fieldMeanings?.['个人成长']||'';return `在“${pos}”的位置，${c.name}${orientation}不是简单给出吉凶，而是在提示：${core}${fieldText?`结合「${state.field}」，${fieldText}`:''}`}
function resultTheme(){const obstacle=state.drawn[state.spread.positions.findIndex(p=>p.includes('阻碍')||p.includes('挑战'))]||state.drawn.find(c=>c.reversed);const helper=state.drawn.find(c=>!c.reversed);return `这组牌的重点不在于给未来盖章，而在于${obstacle?`看清「${obstacle.name}」所代表的${obstacle.reversed?obstacle.reversed:obstacle.upright}`:'辨认你真正能掌握的部分'}。${helper?`「${helper.name}」提示，转机来自${helper.upright}。`:''}`}
function renderResult(){const cardsHtml=state.drawn.map((c,i)=>`<div class="tarot-card" data-reveal="${i}"><div class="tarot-card-inner"><div class="tarot-face tarot-back">☾</div><div class="tarot-face tarot-front ${c.reversed?'reversed':''}"><div class="card-art">${c.icon}</div><small>${c.name} · ${c.reversed?'逆位':'正位'}</small></div></div><div class="tarot-position">${state.spread.positions[i]}</div></div>`).join('');$('#resultView').innerHTML=`<div class="result-hero"><span class="eyebrow">YOUR READING</span><h2>让牌一张张说话</h2><p id="resultTheme">点击牌面，逐张翻开。先留意你的第一感受，再阅读文字。</p></div><div class="selected-cards">${cardsHtml}</div><div class="interpretation" id="interpretation" hidden><div class="reading-block"><h3>整体能量与分牌解析</h3><p>${resultTheme()}</p>${state.drawn.map((c,i)=>`<article class="card-reading"><h4>${state.spread.positions[i]} · ${c.name}${c.reversed?'（逆位）':''}</h4><p>${cardMeaning(c,i)}</p><div class="card-data-grid"><div><b>画面象征</b><span>${c.symbolism}</span></div><div><b>数字含义</b><span>${c.numberMeaning}</span></div><div><b>元素能量</b><span>${c.elementEnergy}</span></div><div><b>行动建议</b><span>${c.actionAdvice}</span></div></div><details><summary>查看分领域解释与自我觉察</summary><div class="domain-meanings">${domainNames.map(name=>`<p><b>${name}</b>${c.fieldMeanings?.[name]||''}</p>`).join('')}</div><p class="reflection"><b>自我觉察问题：</b>${c.reflectionQuestion||c.selfInquiry}</p></details></article>`).join('')}</div><aside class="reading-block"><h3>全局联动</h3><p>${elementInsight()}</p><h3>现实行动建议</h3><div class="advice-list"><div class="advice-item"><b>今天</b><span>${state.drawn[0]?.actionAdvice||'用十分钟写下：这件事中，事实、猜测和感受分别是什么。'}</span></div><div class="advice-item"><b>未来 1–4 周</b><span>选择一个可验证的小行动，并记录它带来的真实反馈，暂时停止反复抽牌。</span></div><div class="advice-item"><b>长期</b><span>${state.drawn.find(c=>c.reflectionQuestion)?.reflectionQuestion||'留意自己是否把安全感交给外界回应；练习建立清晰边界与稳定的自我支持。'}</span></div></div></aside></div><div class="result-actions" id="resultActions" hidden><button class="button button-ghost" id="saveReading">保存到本机</button><button class="button button-primary" id="restartReading">开始新的问题 →</button></div>`;$$('.tarot-card').forEach(c=>c.onclick=()=>revealCard(c));}
function revealCard(el){const i=+el.dataset.reveal;if(i!==state.revealIndex){toast('请按牌阵顺序逐张翻开');return}el.classList.add('revealed');state.revealIndex++;if(state.revealIndex===state.drawn.length){setTimeout(()=>{$('#interpretation').hidden=false;$('#resultActions').hidden=false;$('#resultTheme').textContent=resultTheme();$('#saveReading').onclick=saveReading;$('#restartReading').onclick=resetReading},650)}}
function saveReading(){const records=JSON.parse(localStorage.getItem('moonTarotRecords')||'[]');records.unshift({id:Date.now(),timestamp:Date.now(),field:state.field,question:state.question||'心中默念的问题',spread:state.spread.name,cards:state.drawn.map(c=>`${c.name}${c.reversed?'逆位':''}`)});localStorage.setItem('moonTarotRecords',JSON.stringify(records.slice(0,30)));renderRecords();toast('已安全保存在当前设备')}
function resetReading(){state={field:fields[0][0],question:'',spread:null,shuffled:false,cut:false,drawn:[],revealIndex:0};$('#question').value='';$('#questionCount').textContent='0 / 300';$('#reversalToggle').checked=false;renderFields();renderSpreads();goStage(1)}
function renderLibrary(filter='全部',search=''){const list=cards.filter(c=>(filter==='全部'||c.arcana===filter)&&(!search||`${c.name}${c.theme}${c.uprightText}${c.reversedText}${c.symbolism}${c.actionAdvice}`.includes(search)));$('#cardLibrary').innerHTML=list.map(c=>`<article class="library-card"><i>${c.icon}</i><b>${c.name}</b><small>${c.arcana} · ${c.element}元素 · 数字 ${c.number}</small><p>${c.theme}</p><details><summary>完整牌义</summary><p><b>画面象征：</b>${c.symbolism}</p><p><b>正位：</b>${c.uprightText}</p><p><b>逆位：</b>${c.reversedText}</p><p><b>行动建议：</b>${c.actionAdvice}</p><p><b>觉察问题：</b>${c.reflectionQuestion}</p></details></article>`).join('')||'<div class="empty">没有找到相符的牌</div>'}
function renderRecords(){const rs=JSON.parse(localStorage.getItem('moonTarotRecords')||'[]');$('#recordsList').innerHTML=rs.length?rs.map(r=>`<article class="record"><div><h3>${r.field} · ${r.question}</h3><p>${new Date(r.timestamp).toLocaleString('zh-CN')} · ${r.spread} · ${r.cards.join('、')}</p></div><button class="button button-ghost delete-record" data-id="${r.id}">删除</button></article>`).join(''):'<div class="empty">这里还没有记录。完成一次抽牌后，你可以选择保存。</div>';$$('.delete-record').forEach(b=>b.onclick=()=>{localStorage.setItem('moonTarotRecords',JSON.stringify(rs.filter(r=>r.id!==+b.dataset.id)));renderRecords()})}
function init(){renderFields();renderSpreads();const filters=['全部','大阿卡纳','权杖','圣杯','宝剑','星币'];$('#libraryFilters').innerHTML=filters.map((f,i)=>`<button class="${i===0?'active':''}" data-filter="${f}">${f}</button>`).join('');renderLibrary();renderRecords();$$('[data-back]').forEach(b=>b.onclick=()=>goStage(+b.dataset.back));$('#question').oninput=e=>{$('#questionCount').textContent=`${e.target.value.length} / 180`};$('#toSpreads').onclick=()=>{state.question=$('#question').value.trim();const recent=checkCooldown();if(recent)toast('这个问题刚刚问过。先给答案一点发生的时间，再回来看看。');goStage(2)};$('#toDraw').onclick=()=>{state.drawn=[];state.shuffled=false;state.cut=false;state.revealIndex=0;goStage(3)};$('#shuffleButton').onclick=()=>{state.shuffled=true;$('#deckTable').classList.add('shuffling');$('#shuffleButton').textContent='停止洗牌';$('#shuffleButton').onclick=()=>{state.shuffled=true;$('#deckTable').classList.remove('shuffling');$('#shuffleButton').textContent='已洗牌';$('#shuffleButton').disabled=true;$('#cutButton').disabled=false;$('#drawStatus').textContent='跟随直觉，在你愿意的位置切一次牌'}};$('#cutButton').onclick=()=>{state.cut=true;$('#cutButton').disabled=true;$('#cutButton').textContent='已切牌';$('#drawStatus').textContent=`请亲手选择 ${state.spread.count} 张牌`};$('#revealButton').onclick=()=>{renderResult();goStage(4)};$('#cardSearch').oninput=e=>renderLibrary($('.filter-pills .active').dataset.filter,e.target.value.trim());$$('.filter-pills button').forEach(b=>b.onclick=()=>{$$('.filter-pills button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLibrary(b.dataset.filter,$('#cardSearch').value.trim())});$('.nav-toggle').onclick=()=>{const n=$('.site-nav');n.classList.toggle('open');$('.nav-toggle').setAttribute('aria-expanded',n.classList.contains('open'))};$$('.site-nav a').forEach(a=>a.onclick=()=>$('.site-nav').classList.remove('open'))}
init();
const resultObserver=new MutationObserver(()=>{$$('.tarot-card').forEach((card,i)=>{card.setAttribute('role','button');card.setAttribute('tabindex','0');card.setAttribute('aria-label',`翻开第 ${i+1} 张牌`);card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();revealCard(card)}}})});
resultObserver.observe($('#resultView'),{childList:true,subtree:true});
$('#shuffleButton').addEventListener('click',()=>{if($('#shuffleButton').textContent==='停止洗牌')$('#drawStatus').textContent='牌正在流动。感觉合适时，再点一次停止。'});

const soundscape=(()=>{
  let context,master,drone=[],chimeTimer,enabled=false;
  const ensure=()=>{if(!context){context=new(window.AudioContext||window.webkitAudioContext)();master=context.createGain();master.gain.value=.55;master.connect(context.destination)}if(context.state==='suspended')context.resume();return context};
  const tone=(frequency,duration=.5,volume=.035,type='sine',delay=0)=>{if(!enabled)return;const ctx=ensure(),osc=ctx.createOscillator(),gain=ctx.createGain(),now=ctx.currentTime+delay;osc.type=type;osc.frequency.setValueAtTime(frequency,now);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(volume,now+.035);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(gain).connect(master);osc.start(now);osc.stop(now+duration+.05)};
  const chime=()=>{tone(659.25,2.8,.018,'sine');tone(987.77,2.2,.011,'sine',.12);tone(1318.51,1.8,.006,'sine',.28)};
  const start=()=>{const ctx=ensure();enabled=true;master.gain.cancelScheduledValues(ctx.currentTime);master.gain.setTargetAtTime(.55,ctx.currentTime,.5);[82.41,123.47].forEach((frequency,index)=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=index?'sine':'triangle';osc.frequency.value=frequency;gain.gain.value=index?.009:.012;osc.connect(gain).connect(master);osc.start();drone.push(osc)});chime();chimeTimer=setInterval(chime,12000)};
  const stop=()=>{enabled=false;clearInterval(chimeTimer);if(context){master.gain.setTargetAtTime(.0001,context.currentTime,.3);drone.forEach(osc=>{try{osc.stop(context.currentTime+1)}catch{}});drone=[]}};
  const effect=name=>{if(!enabled)return;if(name==='shuffle'){tone(196,.34,.025,'triangle');tone(293.66,.3,.018,'sine',.08)}if(name==='cut'){tone(246.94,.5,.027,'triangle');tone(369.99,.7,.017,'sine',.08)}if(name==='select'){tone(523.25,.55,.025,'sine');tone(783.99,.75,.012,'sine',.06)}if(name==='flip'){tone(659.25,.7,.028,'sine');tone(987.77,.9,.014,'sine',.08)}};
  return{toggle(){enabled?stop():start();return enabled},effect};
})();

$('#soundToggle').onclick=()=>{const on=soundscape.toggle(),button=$('#soundToggle');button.classList.toggle('active',on);button.setAttribute('aria-pressed',String(on));button.setAttribute('aria-label',on?'关闭氛围音乐':'开启氛围音乐');button.querySelector('span').textContent=on?'♫':'♪';toast(on?'氛围音乐与仪式音效已开启':'声音已关闭')};
document.addEventListener('click',event=>{const target=event.target.closest('button,.tarot-card');if(!target||target.id==='soundToggle')return;if(target.id==='shuffleButton')soundscape.effect('shuffle');else if(target.id==='cutButton')soundscape.effect('cut');else if(target.classList.contains('deck-card')&&target.classList.contains('chosen'))soundscape.effect('select');else if(target.classList.contains('tarot-card'))soundscape.effect('flip')});

// Product flow enhancements: question refinement, safety, recovery and review.
if(!fields.some(field=>field[0]==='个人成长'))fields.splice(6,0,['个人成长','♙','未来三个月，我最值得培养的内在能力是什么？']);
renderFields();

const productState={timeRange:'3_months',background:'',recommendedQuestion:'',recommendedSpread:'three',readingId:'',stage:1};
const timeLabels={current:'当前','1_month':'1个月','3_months':'3个月','6_months':'6个月','1_year':'1年'};
const categoryFocus={情感关系:'这段关系的互动动力',事业发展:'当前职业阶段的机会与阻碍',学业考试:'达成学习目标所需的调整',财务状况:'与资源及安全感相关的现实模式',人际关系:'这段关系中的边界与沟通',人生抉择:'两个方向各自的动力与代价',个人成长:'此阶段最值得发展的内在能力',今日指引:'今天最值得关注的内在主题'};
const riskRules=[
  {type:'紧急安全',pattern:/自杀|自残|伤害自己|杀人|伤害他人/,message:'如果你或他人正面临即时危险，请优先联系当地紧急服务、可信任的人或专业支持。塔罗不适合处理紧急安全问题。'},
  {type:'医疗健康',pattern:/怀孕|癌症|疾病|生病|死亡|还能活|诊断|药物/,message:'塔罗无法确认疾病、怀孕或死亡等医学事实。请以正规检查和医疗专业意见为准。'},
  {type:'法律犯罪',pattern:/坐牢|判刑|犯罪|官司|法律结果|警察会不会/,message:'塔罗不能替代律师意见，也不能确认犯罪或法律结果。'},
  {type:'高风险财务',pattern:/彩票|赌博|梭哈|暴富|股票.*买|投资.*赚/,message:'塔罗不能提供投资、博彩或财务决策依据，请咨询具备资质的专业人士。'},
  {type:'第三方隐私',pattern:/(跟踪|监视|定位|偷看|查手机|他|她).*(秘密|出轨|爱不爱|在哪里|想什么)/,message:'与其试图确认第三方的隐私或想法，更适合把问题转向你能观察、沟通和决定的部分。'}
];
const escapeHTML=value=>String(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const normalizeQuestion=value=>String(value||'').toLowerCase().replace(/[\s，。！？、,.!?]/g,'');
const trackEvent=name=>{const data=JSON.parse(localStorage.getItem('11yTarotMetrics')||'{}');data[name]=(data[name]||0)+1;localStorage.setItem('11yTarotMetrics',JSON.stringify(data))};
const makeReadingId=()=>`${Date.now().toString(36)}-${crypto.getRandomValues(new Uint32Array(2)).join('-')}`;
function similarQuestion(question){const normalized=normalizeQuestion(question);if(!normalized)return null;const records=JSON.parse(localStorage.getItem('moonTarotRecords')||'[]');return records.find(record=>{const old=normalizeQuestion(record.question);const overlap=[...new Set(normalized)].filter(char=>old.includes(char)).length/Math.max(new Set(normalized).size,1);return Date.now()-record.timestamp<86400000&&(old===normalized||overlap>=.82)})}
function improveQuestion(question){const range=$('#timeRange').value==='custom'?($('#customTimeRange').value.trim()||'你设定的时间范围'):timeLabels[$('#timeRange').value]||'未来三个月',focus=categoryFocus[state.field]||'当前问题';if(!question)return `${range}内，${focus}可能如何发展？我需要看清并调整什么？`;if(/[吗？?]$|是否|会不会|能不能|有没有/.test(question)||/^(他|她)/.test(question))return `${range}内，${focus}可能如何变化？我能看清什么，并采取哪些有益行动？`;if(question.length<10)return `${range}内，围绕“${question}”，我需要看清哪些现实因素、内在阻碍与可行行动？`;if(!/月|年|周|天|当前|近期|未来|学期|年底|年初/.test(question))return `${range}内，${question.replace(/[？?。]$/,'')}？我需要关注哪些可改变的部分？`;return question}
function chooseRecommendedSpread(question){if(state.field==='今日指引')return'one';if(state.field==='人生抉择'||/选择|选项|还是|两条路|A|B/.test(question))return'five';if(question.length>70||/长期|复杂|多方面|一年/.test(question))return'celtic';return'three'}
function applySpreadRecommendation(id){productState.recommendedSpread=id;const spread=spreads.find(item=>item.id===id);state.spread=spread;$$('.spread-card').forEach(card=>card.classList.toggle('selected',card.dataset.spread===id));$('#toDraw').disabled=false;$('#spreadRecommendation').hidden=false;$('#spreadRecommendation').innerHTML=`<b>为你推荐：${spread.name}</b><span>${spread.desc} · 预计 ${spread.count===1?'1':spread.count<=3?'3–5':spread.count<=5?'5–8':'10–15'} 分钟</span>`}
function finishQuestion(useRecommended){const chosen=useRecommended?productState.recommendedQuestion:$('#question').value.trim();$('#question').value=chosen;state.question=chosen;productState.timeRange=$('#timeRange').value;productState.background=$('#background').value.trim();productState.readingId=makeReadingId();$('#refinePanel').hidden=true;const repeated=similarQuestion(chosen);goStage(2);applySpreadRecommendation(chooseRecommendedSpread(chosen));if(repeated){$('#spreadRecommendation').insertAdjacentHTML('beforeend','<em>你在24小时内问过相似问题。反复抽牌可能放大焦虑；建议先回看上次结果，确认现实中是否出现了新变化。</em>');trackEvent('repeat_warning_shown')}trackEvent(useRecommended?'question_refine_accepted':'question_submitted');saveDraft(2)}
function inspectQuestion(){const question=$('#question').value.trim(),risk=riskRules.find(rule=>rule.pattern.test(question));$('#riskPanel').hidden=true;$('#refinePanel').hidden=true;if(risk){$('#riskPanel').hidden=false;$('#riskPanel').innerHTML=`<b>${risk.type}问题</b><p>${risk.message}</p><button class="button button-ghost" id="riskRewrite">改为我能采取什么行动</button>`;$('#riskRewrite').onclick=()=>{$('#question').value=`面对当前担忧，我可以采取哪些安全、理性且可验证的行动？`;$('#questionCount').textContent=`${$('#question').value.length} / 300`;$('#riskPanel').hidden=true};trackEvent('risk_question_redirected');return}productState.recommendedQuestion=improveQuestion(question);const changed=productState.recommendedQuestion!==question;if(!changed&&question.length>=10){finishQuestion(false);return}$('#refinePanel').hidden=false;$('#refinePanel').innerHTML=`<span>问题优化建议</span><div><small>原问题</small><p>${escapeHTML(question||'（未填写，在心中默念）')}</p></div><div class="recommended-question"><small>推荐问题</small><p>${escapeHTML(productState.recommendedQuestion)}</p></div><p class="refine-reason">推荐理由：加入时间范围，并把绝对预测转为可观察、可行动的问题。</p><div class="refine-actions"><button class="button button-ghost" id="useOriginal">使用原问题</button><button class="button button-primary" id="useRecommended">使用推荐问题</button></div>`;$('#useOriginal').onclick=()=>finishQuestion(false);$('#useRecommended').onclick=()=>finishQuestion(true)}

$('#question').oninput=event=>{$('#questionCount').textContent=`${event.target.value.length} / 300`;saveDraft(1)};
$('#timeRange').onchange=event=>{const custom=event.target.value==='custom';$('#customTimeRange').hidden=!custom;if(custom)$('#customTimeRange').focus();saveDraft(1)};
$('#toSpreads').onclick=inspectQuestion;
$('#todayQuick').onclick=()=>{state.field='今日指引';renderFields();$$('.field-card').forEach(item=>item.classList.toggle('selected',item.dataset.field==='今日指引'));$('#question').value='今天我最需要关注的内在主题是什么？';$('#questionCount').textContent=`${$('#question').value.length} / 300`;document.querySelector('#reading').scrollIntoView({behavior:'smooth'});trackEvent('home_today_click')};
const coreToDraw=$('#toDraw').onclick;$('#toDraw').onclick=()=>{state.seed=crypto.getRandomValues(new Uint32Array(4)).join('-');productState.stage=3;coreToDraw();trackEvent('spread_selected');saveDraft(3)};

function buildExtendedResult(){const interpretation=$('#interpretation');if(!interpretation||$('#extendedResult'))return;const majorsCount=state.drawn.filter(card=>card.arcana==='大阿卡纳').length,reversed=state.drawn.filter(card=>card.reversed),first=state.drawn[0],last=state.drawn[state.drawn.length-1],obstacleIndex=state.spread.positions.findIndex(position=>/阻碍|挑战|代价/.test(position)),obstacle=state.drawn[obstacleIndex]||reversed[0]||first;const evidence=`${first.name}位于“${state.spread.positions[0]}”，而${last.name}位于“${state.spread.positions.at(-1)}”；同时大阿卡纳占 ${Math.round(majorsCount/state.drawn.length*100)}%。`;interpretation.insertAdjacentHTML('afterend',`<section class="extended-result" id="extendedResult" hidden><div class="reading-block"><h3>现状与未来走向</h3><p>当前牌面从「${first.upright}」走向「${last.reversed?last.reversed:last.upright}」。这表示未来更可能取决于你如何回应当下，而不是一个已经固定的结局。</p><details><summary>为什么这样解读</summary><p>${evidence}</p></details></div><div class="reading-block"><h3>深度心理剖析</h3><p><b>可能的盲点：</b>${obstacle.name}提示，你或许把部分注意力放在无法控制的回应上。</p><p><b>可用资源：</b>${(state.drawn.find(card=>!card.reversed)||first).name}所代表的${(state.drawn.find(card=>!card.reversed)||first).upright}，是当前可主动调用的力量。</p></div><div class="reading-block agency-note"><h3>不确定性与主动权</h3><p>塔罗呈现的是此刻的象征关系与条件性趋势，不是事实认证或不可改变的预言。现实信息、沟通与持续行动，始终比任何一次牌面更重要。</p></div><div class="review-tools reading-block"><h3>保存行动与设定复盘</h3><label>复盘日期<input type="date" id="reviewDate"></label><button class="button button-primary" id="saveAdvice">保存行动计划</button><span id="adviceStatus"></span></div></section>`);$('#saveAdvice').onclick=()=>{const plans=JSON.parse(localStorage.getItem('11yTarotActionPlans')||'[]');plans.unshift({id:productState.readingId||makeReadingId(),question:state.question,reviewAt:$('#reviewDate').value,createdAt:Date.now(),advice:['区分事实、猜测和感受','选择一个可验证的小行动','在复盘日前不为同一问题反复抽牌']});localStorage.setItem('11yTarotActionPlans',JSON.stringify(plans.slice(0,30)));$('#adviceStatus').textContent='已保存在当前设备';trackEvent('advice_saved')}}
const coreRenderResult=renderResult;renderResult=function(){coreRenderResult();buildExtendedResult();productState.stage=4;saveDraft(4)};
const coreRevealCard=revealCard;revealCard=function(element){coreRevealCard(element);trackEvent('card_revealed');if(state.revealIndex===state.drawn.length)setTimeout(()=>{const extended=$('#extendedResult');if(extended)extended.hidden=false;saveDraft(4);trackEvent('interpretation_completed')},720)};

function saveDraft(stage=productState.stage){productState.stage=stage;const payload={timestamp:Date.now(),stage,state:{...state,spread:state.spread?{id:state.spread.id}:null},productState:{...productState},question:$('#question')?.value||'',background:$('#background')?.value||'',timeRange:$('#timeRange')?.value||'3_months',customTimeRange:$('#customTimeRange')?.value||''};localStorage.setItem('11yTarotDraft',JSON.stringify(payload))}
function restoreDraft(){const draft=JSON.parse(localStorage.getItem('11yTarotDraft')||'null');if(!draft||Date.now()-draft.timestamp>86400000)return;Object.assign(productState,draft.productState||{});Object.assign(state,draft.state||{});if(draft.state?.spread)state.spread=spreads.find(spread=>spread.id===draft.state.spread.id)||null;$('#question').value=draft.question||state.question||'';$('#questionCount').textContent=`${$('#question').value.length} / 300`;$('#background').value=draft.background||'';$('#timeRange').value=draft.timeRange||'3_months';$('#customTimeRange').value=draft.customTimeRange||'';$('#customTimeRange').hidden=$('#timeRange').value!=='custom';if(draft.stage===4&&state.spread&&state.drawn?.length===state.spread.count){renderResult();goStage(4);$$('.tarot-card').forEach(card=>card.classList.add('revealed'));state.revealIndex=state.drawn.length;$('#interpretation').hidden=false;$('#resultActions').hidden=false;$('#extendedResult').hidden=false;toast('已恢复上次未关闭的占卜结果')}else if(draft.stage>=2&&state.spread){goStage(2);applySpreadRecommendation(state.spread.id);toast('已恢复上次的提问与牌阵')}}
document.addEventListener('click',event=>{const action=event.target.closest('button');if(action&&['clearRecords','restartReading'].includes(action.id))return;if(event.target.closest('.deck-card'))trackEvent('card_selected');if(action?.id==='shuffleButton')trackEvent('shuffle_started');setTimeout(()=>saveDraft(productState.stage),0)});
$('#clearRecords').onclick=()=>{['moonTarotRecords','11yTarotActionPlans','11yTarotDraft','11yTarotMetrics'].forEach(key=>localStorage.removeItem(key));renderRecords();toast('全部本地占卜数据已删除')};
const coreResetReading=resetReading;resetReading=function(){coreResetReading();Object.assign(productState,{timeRange:'3_months',background:'',recommendedQuestion:'',recommendedSpread:'three',readingId:'',stage:1});$('#timeRange').value='3_months';$('#background').value='';$('#customTimeRange').value='';$('#customTimeRange').hidden=true;$('#refinePanel').hidden=true;$('#riskPanel').hidden=true;localStorage.removeItem('11yTarotDraft')};
restoreDraft();
