const fields=[['情感关系','♡','未来三个月，我们的关系可能如何发展？我需要看清什么？'],['事业发展','♜','在当前事业阶段，我最需要看见的机会与阻碍是什么？'],['学业考试','✎','为了更稳妥地达成学习目标，我现在应调整什么？'],['财务状况','◇','我该如何理解并改善目前与金钱的关系？'],['人际关系','♧','在这段人际关系中，我需要建立怎样的边界？'],['人生抉择','⇄','面对这个选择，什么因素最值得我认真衡量？'],['今日指引','☼','今天我最需要关注的内在主题是什么？']];
const spreads=[{id:'one',name:'单牌指引',count:1,desc:'适合今日提醒或一个清晰、轻量的问题。',positions:['此刻的指引']},{id:'three',name:'三牌阵',count:3,desc:'适合看见事情的脉络：现状、阻碍与建议。',positions:['现状','阻碍','建议']},{id:'five',name:'五牌抉择',count:5,desc:'适合比较两个选项，不替你决定，但照见各自代价。',positions:['你的核心需要','选项 A 的动力','选项 A 的代价','选项 B 的动力','选项 B 的代价']},{id:'celtic',name:'凯尔特十字',count:10,desc:'适合复杂、长期、牵涉多重因素的问题。',positions:['核心现状','交叉挑战','意识目标','深层根源','近期过去','近期趋势','你的姿态','外部环境','希望与恐惧','整合方向']}];
const majors=[['愚人','✧','开放与启程','冲动与失焦'],['魔术师','✦','意志与创造','操控与分散'],['女祭司','☾','直觉与静观','封闭与迟疑'],['皇后','❀','滋养与丰盛','过度给予'],['皇帝','♜','秩序与边界','僵化与控制'],['教皇','⚜','传统与学习','教条与依赖'],['恋人','♡','联结与选择','失衡与逃避'],['战车','♞','推进与掌控','急进与内耗'],['力量','∞','温柔的勇气','压抑与自疑'],['隐士','☼','独处与洞察','孤立与回避'],['命运之轮','⊙','周期与转折','抗拒与重复'],['正义','⚖','诚实与因果','偏见与失衡'],['倒吊人','▽','暂停与换位','停滞与牺牲'],['死神','♱','结束与蜕变','留恋与抗拒'],['节制','⚗','调和与修复','过度与失序'],['恶魔','♑','欲望与束缚','否认与沉溺'],['高塔','ϟ','真相与重构','恐惧改变'],['星星','✵','希望与疗愈','失望与疏离'],['月亮','☽','潜意识与迷雾','焦虑与误读'],['太阳','☀','清晰与生命力','自负与灼热'],['审判','♬','召唤与觉醒','自责与逃避'],['世界','◎','完成与整合','未竟与封闭']];
const suits=[{name:'权杖',icon:'♢',element:'火',theme:'行动、热情与创造力'},{name:'圣杯',icon:'♧',element:'水',theme:'情绪、关系与感受'},{name:'宝剑',icon:'♤',element:'风',theme:'思想、沟通与冲突'},{name:'星币',icon:'⬡',element:'土',theme:'现实、资源与身体'}];
const ranks=[['王牌','新的开端'],['二','选择与平衡'],['三','发展与协作'],['四','稳定与停留'],['五','摩擦与调整'],['六','过渡与互助'],['七','评估与坚持'],['八','推进与限制'],['九','积累与临界'],['十','完成与负担'],['侍从','探索与消息'],['骑士','行动与追寻'],['王后','内在掌握'],['国王','成熟与承担']];
const cards=[...majors.map((c,i)=>({id:`M${i}`,name:c[0],icon:c[1],arcana:'大阿卡纳',element:i===17?'风':i===18?'水':i===19?'火':i===20?'火':'灵',number:i,upright:c[2],reversed:c[3],theme:`${c[2]}所带来的内在转变`})),...suits.flatMap((s,si)=>ranks.map((r,ri)=>({id:`${si}-${ri}`,name:`${s.name}${r[0]}`,icon:s.icon,arcana:s.name,element:s.element,number:ri+1,upright:`${r[1]}中的${s.theme.split('、')[0]}`,reversed:`${s.theme.split('、')[0]}受阻或过度`,theme:`${s.theme}；${r[1]}`})))];
let state={field:fields[0][0],question:'',spread:null,shuffled:false,cut:false,drawn:[],revealIndex:0};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function secureRandom(max){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%max}
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=secureRandom(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function renderFields(){$('#fieldGrid').innerHTML=fields.map((f,i)=>`<button class="field-card ${i===0?'selected':''}" data-field="${f[0]}"><i>${f[1]}</i><span>${f[0]}</span></button>`).join('');$$('.field-card').forEach(b=>b.onclick=()=>{$$('.field-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.field=b.dataset.field;const f=fields.find(x=>x[0]===state.field);$('#question').placeholder=`例如：${f[2]}`})}
function renderSpreads(){$('#spreadGrid').innerHTML=spreads.map(s=>`<button class="spread-card" data-spread="${s.id}"><span class="count">${s.count} 张牌</span><div class="spread-visual">${Array.from({length:Math.min(s.count,6)},()=>'<i></i>').join('')}</div><h3>${s.name}</h3><p>${s.desc}</p></button>`).join('');$$('.spread-card').forEach(b=>b.onclick=()=>{$$('.spread-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.spread=spreads.find(s=>s.id===b.dataset.spread);$('#toDraw').disabled=false})}
function goStage(n){$$('.reading-stage').forEach(s=>s.classList.toggle('active',+s.dataset.stage===n));$$('.progress-step').forEach((s,i)=>{s.classList.toggle('active',i===n-1);s.classList.toggle('done',i<n-1)});document.querySelector('#reading').scrollIntoView({behavior:'smooth'});if(n===3)renderDeck()}
function checkCooldown(){const q=state.question.trim().toLowerCase();if(!q)return false;const records=JSON.parse(localStorage.getItem('moonTarotRecords')||'[]');const recent=records.find(r=>r.question.trim().toLowerCase()===q&&Date.now()-r.timestamp<21600000);return recent}
function renderDeck(){const table=$('#deckTable');table.innerHTML=Array.from({length:26},(_,i)=>`<button class="deck-card" aria-label="选择第 ${i+1} 张牌" style="transform:translateX(${(i-12.5)*Math.min(15,260/26)}px) rotate(${(i-12.5)*.8}deg);z-index:${i}" data-index="${i}"></button>`).join('');$$('.deck-card').forEach(c=>c.onclick=()=>chooseCard(c));$('#drawStatus').textContent=state.shuffled?(state.cut?'请从牌面中亲手选择':'你可以切一次牌，然后开始选择'):'准备好后，请先洗牌'}
function chooseCard(el){if(!state.shuffled)return toast('请先洗牌');if(!state.cut)return toast('先完成一次切牌，让选择更有仪式感');if(state.drawn.length>=state.spread.count)return;const remaining=cards.filter(c=>!state.drawn.some(d=>d.id===c.id));const card=remaining[secureRandom(remaining.length)];state.drawn.push({...card,reversed:$('#reversalToggle').checked&&secureRandom(2)===1});el.classList.add('chosen');const left=state.spread.count-state.drawn.length;$('#drawStatus').textContent=left?`已选择 ${state.drawn.length} 张，还需 ${left} 张`:`已选好 ${state.spread.count} 张牌。准备好后，逐张翻开。`;$('#revealButton').disabled=left!==0}
function elementInsight(){const counts={};state.drawn.forEach(c=>counts[c.element]=(counts[c.element]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];const major=state.drawn.filter(c=>c.arcana==='大阿卡纳').length;return `${top?`${top[0]}元素最突出，说明当前议题尤其牵动${{火:'行动与意愿',水:'情绪与关系',风:'思考与沟通',土:'现实与安全感',灵:'深层人生课题'}[top[0]]}。`:''}${major>=Math.ceil(state.drawn.length/2)?'大阿卡纳占比较高，这更像一次需要认真整合的人生课题，而非短暂波动。':'这组牌更关注可以被日常行动调整的具体处境。'}`}
function cardMeaning(c,i){const pos=state.spread.positions[i];const key=c.reversed?c.reversed:c.upright;return `在“${pos}”的位置，${c.name}${c.reversed?'逆位':'正位'}提醒你关注${key}。放进「${state.field}」这个问题里，它并不宣布结果，而是在指出：你当前的选择可能正被这一股力量推动。`}
function resultTheme(){const obstacle=state.drawn[state.spread.positions.findIndex(p=>p.includes('阻碍')||p.includes('挑战'))]||state.drawn.find(c=>c.reversed);const helper=state.drawn.find(c=>!c.reversed);return `这组牌的重点不在于给未来盖章，而在于${obstacle?`看清「${obstacle.name}」所代表的${obstacle.reversed?obstacle.reversed:obstacle.upright}`:'辨认你真正能掌握的部分'}。${helper?`「${helper.name}」提示，转机来自${helper.upright}。`:''}`}
function renderResult(){const cardsHtml=state.drawn.map((c,i)=>`<div class="tarot-card" data-reveal="${i}"><div class="tarot-card-inner"><div class="tarot-face tarot-back">☾</div><div class="tarot-face tarot-front ${c.reversed?'reversed':''}"><div class="card-art">${c.icon}</div><small>${c.name} · ${c.reversed?'逆位':'正位'}</small></div></div><div class="tarot-position">${state.spread.positions[i]}</div></div>`).join('');$('#resultView').innerHTML=`<div class="result-hero"><span class="eyebrow">YOUR READING</span><h2>让牌一张张说话</h2><p id="resultTheme">点击牌面，逐张翻开。先留意你的第一感受，再阅读文字。</p></div><div class="selected-cards">${cardsHtml}</div><div class="interpretation" id="interpretation" hidden><div class="reading-block"><h3>整体能量与分牌解析</h3><p>${resultTheme()}</p>${state.drawn.map((c,i)=>`<article class="card-reading"><h4>${state.spread.positions[i]} · ${c.name}${c.reversed?'（逆位）':''}</h4><p>${cardMeaning(c,i)}</p><details><summary>深入了解象征与原型</summary><p>${c.name}属于${c.arcana}，对应${c.element}元素与数字 ${c.number}。它的核心主题是：${c.theme}。请把它当作观察角度，而非唯一答案。</p></details></article>`).join('')}</div><aside class="reading-block"><h3>全局联动</h3><p>${elementInsight()}</p><h3>现实行动建议</h3><div class="advice-list"><div class="advice-item"><b>今天</b><span>用十分钟写下：这件事中，事实、猜测和感受分别是什么。</span></div><div class="advice-item"><b>未来 1–4 周</b><span>选择一个可验证的小行动，并记录它带来的真实反馈，暂时停止反复抽牌。</span></div><div class="advice-item"><b>长期</b><span>留意自己是否把安全感交给外界回应；练习建立清晰边界与稳定的自我支持。</span></div></div></aside></div><div class="result-actions" id="resultActions" hidden><button class="button button-ghost" id="saveReading">保存到本机</button><button class="button button-primary" id="restartReading">开始新的问题 →</button></div>`;$$('.tarot-card').forEach(c=>c.onclick=()=>revealCard(c));}
function revealCard(el){const i=+el.dataset.reveal;if(i!==state.revealIndex){toast('请按牌阵顺序逐张翻开');return}el.classList.add('revealed');state.revealIndex++;if(state.revealIndex===state.drawn.length){setTimeout(()=>{$('#interpretation').hidden=false;$('#resultActions').hidden=false;$('#resultTheme').textContent=resultTheme();$('#saveReading').onclick=saveReading;$('#restartReading').onclick=resetReading},650)}}
function saveReading(){const records=JSON.parse(localStorage.getItem('moonTarotRecords')||'[]');records.unshift({id:Date.now(),timestamp:Date.now(),field:state.field,question:state.question||'心中默念的问题',spread:state.spread.name,cards:state.drawn.map(c=>`${c.name}${c.reversed?'逆位':''}`)});localStorage.setItem('moonTarotRecords',JSON.stringify(records.slice(0,30)));renderRecords();toast('已安全保存在当前设备')}
function resetReading(){state={field:fields[0][0],question:'',spread:null,shuffled:false,cut:false,drawn:[],revealIndex:0};$('#question').value='';$('#questionCount').textContent='0 / 180';$('#reversalToggle').checked=false;renderFields();renderSpreads();goStage(1)}
function renderLibrary(filter='全部',search=''){const list=cards.filter(c=>(filter==='全部'||c.arcana===filter)&&(!search||`${c.name}${c.theme}${c.upright}`.includes(search)));$('#cardLibrary').innerHTML=list.map(c=>`<article class="library-card"><i>${c.icon}</i><b>${c.name}</b><small>${c.arcana} · ${c.element}元素</small></article>`).join('')||'<div class="empty">没有找到相符的牌</div>'}
function renderRecords(){const rs=JSON.parse(localStorage.getItem('moonTarotRecords')||'[]');$('#recordsList').innerHTML=rs.length?rs.map(r=>`<article class="record"><div><h3>${r.field} · ${r.question}</h3><p>${new Date(r.timestamp).toLocaleString('zh-CN')} · ${r.spread} · ${r.cards.join('、')}</p></div><button class="button button-ghost delete-record" data-id="${r.id}">删除</button></article>`).join(''):'<div class="empty">这里还没有记录。完成一次抽牌后，你可以选择保存。</div>';$$('.delete-record').forEach(b=>b.onclick=()=>{localStorage.setItem('moonTarotRecords',JSON.stringify(rs.filter(r=>r.id!==+b.dataset.id)));renderRecords()})}
function init(){renderFields();renderSpreads();const filters=['全部','大阿卡纳','权杖','圣杯','宝剑','星币'];$('#libraryFilters').innerHTML=filters.map((f,i)=>`<button class="${i===0?'active':''}" data-filter="${f}">${f}</button>`).join('');renderLibrary();renderRecords();$$('[data-back]').forEach(b=>b.onclick=()=>goStage(+b.dataset.back));$('#question').oninput=e=>{$('#questionCount').textContent=`${e.target.value.length} / 180`};$('#toSpreads').onclick=()=>{state.question=$('#question').value.trim();const recent=checkCooldown();if(recent)toast('这个问题刚刚问过。先给答案一点发生的时间，再回来看看。');goStage(2)};$('#toDraw').onclick=()=>{state.drawn=[];state.shuffled=false;state.cut=false;state.revealIndex=0;goStage(3)};$('#shuffleButton').onclick=()=>{state.shuffled=true;$('#deckTable').classList.add('shuffling');$('#shuffleButton').textContent='停止洗牌';$('#shuffleButton').onclick=()=>{state.shuffled=true;$('#deckTable').classList.remove('shuffling');$('#shuffleButton').textContent='已洗牌';$('#shuffleButton').disabled=true;$('#cutButton').disabled=false;$('#drawStatus').textContent='跟随直觉，在你愿意的位置切一次牌'}};$('#cutButton').onclick=()=>{state.cut=true;$('#cutButton').disabled=true;$('#cutButton').textContent='已切牌';$('#drawStatus').textContent=`请亲手选择 ${state.spread.count} 张牌`};$('#revealButton').onclick=()=>{renderResult();goStage(4)};$('#cardSearch').oninput=e=>renderLibrary($('.filter-pills .active').dataset.filter,e.target.value.trim());$$('.filter-pills button').forEach(b=>b.onclick=()=>{$$('.filter-pills button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLibrary(b.dataset.filter,$('#cardSearch').value.trim())});$('.nav-toggle').onclick=()=>{const n=$('.site-nav');n.classList.toggle('open');$('.nav-toggle').setAttribute('aria-expanded',n.classList.contains('open'))};$$('.site-nav a').forEach(a=>a.onclick=()=>$('.site-nav').classList.remove('open'))}
init();
const resultObserver=new MutationObserver(()=>{$$('.tarot-card').forEach((card,i)=>{card.setAttribute('role','button');card.setAttribute('tabindex','0');card.setAttribute('aria-label',`翻开第 ${i+1} 张牌`);card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();revealCard(card)}}})});
resultObserver.observe($('#resultView'),{childList:true,subtree:true});
$('#shuffleButton').addEventListener('click',()=>{if($('#shuffleButton').textContent==='停止洗牌')$('#drawStatus').textContent='牌正在流动。感觉合适时，再点一次停止。'});

const soundscape=(()=>{
  let context,master,drone=[],chimeTimer,enabled=false;
  const ensure=()=>{if(!context){context=new(window.AudioContext||window.webkitAudioContext)();master=context.createGain();master.gain.value=.55;master.connect(context.destination)}if(context.state==='suspended')context.resume();return context};
  const tone=(frequency,duration=.5,volume=.035,type='sine',delay=0)=>{if(!enabled)return;const ctx=ensure(),osc=ctx.createOscillator(),gain=ctx.createGain(),now=ctx.currentTime+delay;osc.type=type;osc.frequency.setValueAtTime(frequency,now);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(volume,now+.035);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(gain).connect(master);osc.start(now);osc.stop(now+duration+.05)};
  const chime=()=>{tone(659.25,2.8,.018,'sine');tone(987.77,2.2,.011,'sine',.12);tone(1318.51,1.8,.006,'sine',.28)};
  const start=()=>{const ctx=ensure();enabled=true;master.gain.cancelScheduledValues(ctx.currentTime);master.gain.setTargetAtTime(.55,ctx.currentTime,.5);[82.41,123.47].forEach((frequency,index)=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=index?'sine':'triangle';osc.frequency.value=frequency;gain.gain.value=index?.009:.012;osc.connect(gain).connect(master);osc.start();drone.push(osc)});chime();chimeTimer=setInterval(chime,12000)};
  const stop=()=>{enabled=false;clearInterval(chimeTimer);if(context){master.gain.setTargetAtTime(.0001,context.currentTime,.3);drone.forEach(osc=>{try{osc.stop(context.currentTime+1)}catch{}});drone=[]}};
  const effect=name=>{if(!enabled)return;if(name==='shuffle'){tone(196,.34,.025,'triangle');tone(293.66,.3,.018,'sine',.08)}if(name==='cut'){tone(246.94,.5,.027,'triangle');tone(369.99,.7,.017,'sine',.08)}if(name==='select'){tone(523.25,.55,.025,'sine');tone(783.99,.75,.012,'sine',.06)}if(name==='flip'){tone(659.25,.7,.028,'sine');tone(987.77,.9,.014,'sine',.08)}};
  return{toggle(){enabled?stop():start();return enabled},effect};
})();

$('#soundToggle').onclick=()=>{const on=soundscape.toggle(),button=$('#soundToggle');button.classList.toggle('active',on);button.setAttribute('aria-pressed',String(on));button.setAttribute('aria-label',on?'关闭氛围音乐':'开启氛围音乐');button.querySelector('span').textContent=on?'♫':'♪';toast(on?'氛围音乐与仪式音效已开启':'声音已关闭')};
document.addEventListener('click',event=>{const target=event.target.closest('button,.tarot-card');if(!target||target.id==='soundToggle')return;if(target.id==='shuffleButton')soundscape.effect('shuffle');else if(target.id==='cutButton')soundscape.effect('cut');else if(target.classList.contains('deck-card')&&target.classList.contains('chosen'))soundscape.effect('select');else if(target.classList.contains('tarot-card'))soundscape.effect('flip')});
